<?php

/**
 * CartuchoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CartuchoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CartuchoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cartucho');
    }
}