<?php

/**
 * CidadeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CidadeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CidadeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cidade');
    }
}