<?php

/**
 * ClienteResponsavelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClienteResponsavelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClienteResponsavelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClienteResponsavel');
    }
}