<?php

/**
 * CondicaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CondicaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CondicaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Condicao');
    }
}