<?php

/**
 * CondicaoPagamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CondicaoPagamentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CondicaoPagamentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CondicaoPagamento');
    }
}