<?php

/**
 * ContratoEquipamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContratoEquipamentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContratoEquipamentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContratoEquipamento');
    }
}