<?php

/**
 * ContratoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContratoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContratoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contrato');
    }
}