<?php

/**
 * EntradaFornecedorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EntradaFornecedorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EntradaFornecedorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EntradaFornecedor');
    }
}