<?php

/**
 * EquipamentoSituacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EquipamentoSituacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EquipamentoSituacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EquipamentoSituacao');
    }
}