<?php

/**
 * EquipamentoModeloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EquipamentoModeloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EquipamentoModeloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EquipamentoModelo');
    }
}