<?php

/**
 * EquipamentoProblemaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EquipamentoProblemaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EquipamentoProblemaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EquipamentoProblema');
    }
}