<?php

/**
 * EquipamentoCondicaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EquipamentoCondicaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EquipamentoCondicaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EquipamentoCondicao');
    }
}