<?php

/**
 * EquipamentoSuporteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EquipamentoSuporteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EquipamentoSuporteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EquipamentoSuporte');
    }
}