<?php

/**
 * FechamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FechamentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FechamentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Fechamento');
    }
}