<?php

/**
 * FinalizarOrdemServicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FinalizarOrdemServicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FinalizarOrdemServicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FinalizarOrdemServico');
    }
}