<?php

/**
 * FornecedorEquipamentoTipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FornecedorEquipamentoTipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FornecedorEquipamentoTipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FornecedorEquipamentoTipo');
    }
}