<?php

/**
 * FornecedorMaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FornecedorMaterialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FornecedorMaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FornecedorMaterial');
    }
}