<?php

/**
 * FornecedorResponsavelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FornecedorResponsavelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FornecedorResponsavelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FornecedorResponsavel');
    }
}