<?php

/**
 * IdTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IdTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IdTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Id');
    }
}