<?php

/**
 * LancamentoTipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LancamentoTipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LancamentoTipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LancamentoTipo');
    }
}