<?php

/**
 * LancamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LancamentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LancamentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lancamento');
    }
}