<?php

/**
 * MaterialEquipamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaterialEquipamentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaterialEquipamentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaterialEquipamento');
    }
}