<?php

/**
 * MensagemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MensagemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MensagemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mensagem');
    }
}