<?php

/**
 * MovimentacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MovimentacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MovimentacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Movimentacao');
    }
}