<?php

/**
 * MovimentacaoTipoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MovimentacaoTipoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MovimentacaoTipoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MovimentacaoTipo');
    }
}