<?php

/**
 * NotaItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotaItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotaItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotaItem');
    }
}