<?php

/**
 * NumeradorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NumeradorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NumeradorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Numerador');
    }
}