<?php

/**
 * OrdemServAcessoremotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdemServAcessoremotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdemServAcessoremotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdemServAcessoremoto');
    }
}