<?php

/**
 * OrdemServInstalacaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdemServInstalacaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdemServInstalacaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdemServInstalacao');
    }
}