<?php

/**
 * OrdemServTonerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdemServTonerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdemServTonerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdemServToner');
    }
}