<?php

/**
 * OrdemServTrocaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdemServTrocaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdemServTrocaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdemServTroca');
    }
}