<?php

/**
 * OrdemServicoCopyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdemServicoCopyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdemServicoCopyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdemServicoCopy');
    }
}