<?php

/**
 * OrdemServNumeradorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdemServNumeradorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdemServNumeradorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdemServNumerador');
    }
}