<?php

/**
 * OrdemServPreventivaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdemServPreventivaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdemServPreventivaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdemServPreventiva');
    }
}