<?php

/**
 * OrdemServico1Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdemServico1Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdemServico1Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdemServico1');
    }
}