<?php

/**
 * OrdemServManutencaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdemServManutencaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OrdemServManutencaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrdemServManutencao');
    }
}