<?php

/**
 * ReciboEquipamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReciboEquipamentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReciboEquipamentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReciboEquipamento');
    }
}