<?php

/**
 * SaidaMaterialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SaidaMaterialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SaidaMaterialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SaidaMaterial');
    }
}