<?php

/**
 * SaidaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SaidaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SaidaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Saida');
    }
}