<?php

/**
 * SuporteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SuporteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SuporteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Suporte');
    }
}