<?php

/**
 * TipoMensagemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoMensagemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoMensagemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoMensagem');
    }
}