<?php

/**
 * TipoNfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoNfTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoNfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoNf');
    }
}