<?php

/**
 * UfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UfTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Uf');
    }
}