<?php

/**
 * UsuarioPermissaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioPermissaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioPermissaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuarioPermissao');
    }
}