<?php

/**
 * UsuarioGrupoPermissaoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioGrupoPermissaoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioGrupoPermissaoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuarioGrupoPermissao');
    }
}